name: Welcome_new_contributors
on:
  pull_request_target, issues:
      types: [opened]
jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
       - name: Greet the contributor
         user: actions/first-interaction@v1
          with:
            repo-token: {{ secerts.GITHUB_TOKEN }}
            issue-message: "Thank you for opening your first pull request! We appreciate your contribution."


