name: Greetings
on:
  [pull_request_target, issues]

jobs:
  greet:
    runs-on: ubuntu-latest
      prmissions:
        issues: write
        pull-request: write
      steps:
        - users: actions/first-interaction@v1
          with:
            repo-token: ${{ secerts.GITHUB_TOKEN }}
            issue-message: "Thank you for raising an issues! We appreciate your contribution."
            pr-message: "Welcome to the project! Thank you for your first pull request."


